version: '3'
services:
  proxy:
    build: ./
    networks:
#      - banca5corporate
      - banca5extranet
    ports:
      - 80:80
    restart: always

networks:
  banca5corporate:
    external:
      name: banca5corporate_default
  banca5extranet:
    external:
      name: banca5extranet_default
