#!/usr/bin/env bash

. common

# Export container db into local sql

echo "List all container with suffix -mysql"
#list all container with suffix -mysql in running status
docker ps -a --filter "name=-mysql" --filter status=running --format {{.Names}}

echo -n "Choose mysql container to backup database: "
read mysqlContainer

echo "Show databases in $mysqlContainer"
docker exec -it "$mysqlContainer" mysql -u root -proot -e "show databases;"

echo -n "Choose database to dump: "
read database

date=`date +"%Y%m%d"`
echo "Creating database dump: $date-$database.sql"
docker exec -i "$mysqlContainer" mysqldump -u root "$database" > "$date"-"$database".sql &
spinner
