#!/usr/bin/env bash

. `pwd`/docker-config/config.sh
. common

# Check Docker daemon is available
checkDockerStatus
choiceBranch
choiceSynchronizeAssets

read -p "How do you want start project ?[local/db-shared/compose] " env
checkEnvirnonment=true
while $checkEnvirnoment; do
    case $env in
        local ) startLocal "$projectInput" "$branchInput"
                checkEnvirnoment=false
                ;;
        remote ) startRemote
                 checkEnvirnoment=false
                 ;;
        db-shared ) startDbShared "$projectInput"
                 checkEnvirnoment=false
                 ;;
        compose ) startCompose "$projectInput" "$branchInput"
                 checkEnvirnoment=false
                 ;;
        * ) read -p "Retype envirnoment: " env
            ;;
    esac
done



